version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-bluesky
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: blueskydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  debt_manager:
    container_name: bluesky
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: blueskyauthentication:1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    expose:
      - ${CONTAINER_PORT}
    ports:
      - "${CONTAINER_PORT}:${HOST_PORT}"
    depends_on:
      - postgres

volumes:
  postgres-data:
